### ISSUE TITLE
choose which app mockmocklocations

### ISSUE THREAD

**Issue by ghost** [bnalls33/MockMockLocations#1]
some app need mock location on in developer options to work on,And your mockmocklocations tell all app this option is off..

**Comment by dreadloke** [comment]
Hi,

A whitelist system would be nice yeah.

Regards

**Comment by bnalls33** [comment]
Thanks would be nice to

**Comment by kayraucklnc** [comment]
I really need it. How can i do? Another app? Changing code of app? I need it for Pokemon GO. But not need for Fake Gps app

**Comment by bnalls33** [comment]
Done. I added a whitelist. I don't know why that would help with Pokemon....

**Comment by dreadloke** [comment]
Thanks for your great work.
Sorry for not being polite at first ;)
